kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-config
  namespace: rhdh
data:
  argocd-config.yaml: |
    argocd:
      username: ${ARGOCD_USER}
      password: ${ARGOCD_PASSWORD}
      waitCycles: 25
      appLocatorMethods:
        - type: 'config'
          instances:
            - name: default
              url: https://${ARGOCD_HOSTNAME}
              token: ${ARGOCD_API_TOKEN}