apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  annotations:
    helm.sh/resource-policy: keep
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: gitops-1.12
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  config:
    env:
      - name: ARGOCD_CLUSTER_CONFIG_NAMESPACES
        value: openshift-gitops,{{ .Release.Namespace }}